### ISSUE TITLE
各種要求権限がdeniedになる

### ISSUE THREAD

**Issue by Mitsutan** [Mitsutan/sysdev_suretti#64]
Android12にて[permission_handler](https://pub.dev/packages/permission_handler)で位置情報、bluetooth権限を要求するも最初から拒否される
許可を求めるダイアログも出ない
すれ違い機能が動作しないのはこのためかもしれない

**Comment by Mitsutan** [comment]
```shell
[PermissionStatus] {Permission.location: PermissionStatus.denied, Permission.locationAlways: PermissionStatus.denied, Permission.locationWhenInUse: PermissionStatus.denied, Permission.bluetoothScan: PermissionStatus.denied, Permission.bluetoothAdvertise: PermissionStatus.denied}
```

```shell
E/BeaconTransmitter( 2828): Cannot start advertising due to exception
E/BeaconTransmitter( 2828): java.lang.SecurityException: Need android.permission.BLUETOOTH_ADVERTISE permission for android.content.AttributionSource@bd9cbecf: GattService startAdvertisingSet
E/BeaconTransmitter( 2828): 	at com.android.bluetooth.Utils.checkPermissionForDataDelivery(Utils.java:457)
E/BeaconTransmitter( 2828): 	at com.android.bluetooth.Utils.checkAdvertisePermissionForDataDelivery(Utils.java:545)
E/BeaconTransmitter( 2828): 	at com.android.bluetooth.gatt.GattService.startAdvertisingSet(GattService.java:3474)
E/BeaconTransmitter( 2828): 	at com.android.bluetooth.gatt.GattService$BluetoothGattBinder.startAdvertisingSet(GattService.java:1484)
E/BeaconTransmitter( 2828): 	at com.android.bluetooth.gatt.GattService$BluetoothGattBinder.startAdvertisingSet(GattService.java:1468)
E/BeaconTransmitter( 2828): 	at android.bluetooth.IBluetoothGatt$Stub.onTransact(IBluetoothGatt.java:620)
E/BeaconTransmitter( 2828): 	at android.os.Binder.execTransactInternal(Binder.java:1285)
E/BeaconTransmitter( 2828): 	at android.os.Binder.execTransact(Binder.java:1244)
```

**Comment by Mitsutan** [comment]
#69 で権限の問題は一応解決
